### ISSUE TITLE
Experimental data

### ISSUE THREAD

**Issue by ayushi1212** [takeuchi-lab/MS-DA-MIL-CNN#2]
Hey, experimental data is mentioned in this Github, and all the format of the scripts are on the basis of that data. So could the data be available please?

**Comment by xuwanyan1998** [comment]
@takeuchi-write could you please release the data you used in your project? that will be very helpful

**Comment by takeuchi-write** [comment]
Thank you for a comment. Unfortunately the database that we used in the experiment is private one and cannot be published. 
Tiled ROI images from WSI data in TCGA database or other public database are similarly available.

Now we are considering to publish a new source code to handle original WSI files.
