### ISSUE TITLE
randomly sampled test bags

### ISSUE THREAD

**Issue by meredith-wenjunwu** [takeuchi-lab/MS-DA-MIL-CNN#3]
Hi, 

Thanks for sharing your code! I have a question regarding how your bag and patches were extracted for the test set @takeuchi-write. 

Did you randomly sampled patches from WSI to get the test set or you used every patch in the image? If it's the latter, does that mean the maximum number of bags in the test set could be larger than 50?

Thanks!
Meredith

**Comment by takeuchi-write** [comment]
@meredith-wenjunwu 
Thank you for your comment, and sorry for our late reply.

Yes, we randomly sampled patches in our experiment. 
However, the maximum number of bags is also available as you mentioned. 
(e.g. set to 1000 bags in testing for using the maximum bags)

For visualization of attention weights, using the maximum number of bags is better for a good visualization.
